# Generated by Django 5.0.7 on 2024-10-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('shipping_address', models.CharField(max_length=50, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('outfit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.add_outfit_designs')),
                ('tailor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tailor_registration')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_registration')),
            ],
        ),
    ]
