# Generated by Django 5.0.7 on 2024-10-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_work_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_request',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
