# Generated by Django 5.0.7 on 2024-10-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_work_request_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_request',
            name='accept_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work_request',
            name='accepted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='work_request',
            name='request_on',
            field=models.DateTimeField(null=True),
        ),
    ]
