# Generated by Django 5.0.7 on 2024-10-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_work_request_accept_status_work_request_accepted_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_request',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work_request',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='work_request',
            name='quantity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
