# Generated by Django 5.0.7 on 2024-10-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_work_request_payment_status_work_request_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_request',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
