# Generated by Django 5.0.7 on 2024-10-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_message_to_tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, null=True)),
                ('message_on', models.DateTimeField(null=True)),
                ('reply', models.CharField(max_length=100, null=True)),
                ('reply_on', models.DateTimeField(null=True)),
                ('tailor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tailor_registration')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_registration')),
            ],
        ),
    ]
